### ISSUE TITLE
Avoid the need for noredirectpatch.txt

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_login#3]
I was originally going to suggest that noredirectpatch.txt be renamed as noredirectpatch.diff so github does it's magic, like these:

https://github.com/catalyst/moodle-tool_objectfs/blob/MOODLE_310_STABLE/patch/core38.diff

But then I realized you can probably remove the patch completely by detecting the page we are on inside the local_login_after_config callback and temp unsetting $CFG->alternateloginurl

**Comment by danmarsden** [comment]
yeah - I had the same thought - there should be a way to build this without needing to copy that page, but we have that patch on all our local sites but I needed to quickly drop something into this plugin that I knew would work for a system we don't have access to and I had minutes rather than days to get it working... ;-)

**Comment by brendanheywood** [comment]
I expect we'll probably pick this up in a few weeks, and some of the other issues too

**Comment by sumaiyamannan** [comment]
Check the PR for it
